name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo
      - run: rustup update stable && rustup default stable
      - run: cargo install --git https://github.com/uiua-lang/uiua uiua
      - run: |
          source test.sh
          for DAY in $(ls -d [0-9][0-9]); do
            echo "### Day ${DAY}"
            run_tests_for_day ${DAY}
            echo
          done

